name: Test/Deploy

on:
  workflow_dispatch:

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: |
          ${{ steps.matrix.outputs.matrix }}        
    steps:
        - name: Outputs matrix
          id: matrix
          run: |
              ips="${{ vars.DISTINCT_IPS }}"
              matrix=$(echo $ips | jq -cR 'split (",") | .[]' | jq -s '[.[] | { machine: . }]' | jq -c '{ include: . }')
              # echo "matrix=$ips" >> "$GITHUB_OUTPUT"
              echo "matrix={\"include\":[{\"machine\":\"1.2.3.4\"},{\"machine\":\"2.3.4.5\"}]}" >> "$GITHUB_OUTPUT"
              echo $matrix

  machine:
    name: Team
    needs: [matrix]
    runs-on: ubuntu-latest
    if: ${{ fromJson(needs.matrix.outputs.matrix).include[0] }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
        - name: Show value
          run: echo ${{ matrix.machine }}
