name: Conditional inside a step

on:
  workflow_dispatch:
    inputs:
      word:
        type: string
        default: ''
jobs:
  machine:
    name: Team
    runs-on: ubuntu-latest
    steps:
        - name: Show value
          run: echo ${{ if inputs.word != '' then concat('--env=', inputs.word) end }}
