name: Conditional inside a step

on:
  workflow_dispatch:
    inputs:
      entorno:
        required: true
        description: entorno puede ser 'vacio', 'pre', 'prod'
        default: ''
        type: string
jobs:
  machine:
    name: Team
    runs-on: ubuntu-latest
    steps:
      - name: Show value
        shell: bash
        run: |
          paramenv=" $([[ -n "${{ github.event.inputs.ENTORNO }}" ]] && echo "--env=${{ github.event.inputs.ENTORNO }}")"
          echo $paramenv
