name: Conditional inside a step

on:
  workflow_dispatch:
    inputs:
      entorno:
        type: string
        default: ''

jobs:
  machine:
    name: Team
    runs-on: ubuntu-latest
    env:
      ENTORNO: |
        ${{ inputs.entorno != "" && ("--env=" + inputs.entorno) }}
    steps:
      - name: Show value
        run: |
          paramenv=$ENTORNO
          echo $paramenv
