name: Conditional inside a step

on:
  workflow_dispatch:
    inputs:
      word:
        type: string
        default: ''

jobs:
  machine:
    name: Team
    runs-on: ubuntu-latest
    steps:
      - name: Show value
        run: |
          paramenv=$([ ${{ inputs.word }}  ] && echo "--env=${{ inputs.word }}")
          echo $paramenv
