name: Conditional inside a step

on:
  workflow_dispatch:
    inputs:
      entorno:
        type: string
        default: ''

jobs:
  machine:
    name: Team
    runs-on: ubuntu-latest
    env:
      ENTORNO: ${{ inputs.ENTORNO   }}
    steps:
      - name: Show value
        shell: bash
        run: |
          paramenv=" $([[ -n "${{ github.event.inputs.ENTORNO }}" ]] && echo "--env=${{ github.event.inputs.ENTORNO }}")"
          echo $paramenv
