name: Conditional inside a step

on:
  workflow_dispatch:
    inputs:
      entorno:
        required: true
        default: ''
        type: choice
        options:
          - ''
          - pre
          - prod
jobs:
  machine:
    name: Team
    runs-on: ubuntu-latest
    steps:
      - name: Show value
        shell: bash
        run: |
          paramenv=" $([[ -n "${{ github.event.inputs.ENTORNO }}" ]] && echo "--env=${{ github.event.inputs.ENTORNO }}")"
          echo $paramenv
