name: Testing Jobs
on:
  workflow_dispatch:

jobs:
  PrimerJob:
    runs-on: ubuntu-latest
    steps:
    - name: Exec ok
      run: echo 'ok'
  SegundoJob:
    runs-on: ubuntu-latest
    steps:
    - name: Exec fail
      run: exit 1
  WaitJob:
    needs: [PrimerJob, SegundoJob]
    if: needs.PrimerJob.status == 'success' || needs.PrimerJob.status == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Exec fail
      run: echo 'todo ok'
