name: Testing Jobs
on:
  workflow_dispatch:

jobs:
  PrimerJob:
    runs-on: ubuntu-latest
    steps:
    - name: Exec fail
      run: echo 'fail'
    - name: Exec fail
      run: exit 1
  SegundoJob:
    runs-on: ubuntu-latest
    steps:
    - name: Exec fail
      run: exit 1
  WaitJob:
    needs: [PrimerJob, SegundoJob]
    if: ${{ always() && (needs.PrimerJob.result == 'success' || needs.SegundoJob.result == 'success') }}
    runs-on: ubuntu-latest
    steps:
    - name: Exec fail
      run: echo 'todo ok'
